name: CI

on:
    workflow_dispatch:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    test:
        name: Test
        runs-on: ubuntu-22.04
        #===================
        # TODO: Optimize the matrix strategy to run job only for changed service
        #===================
        strategy:
            fail-fast: false
            matrix:
                service: [frontend, backend]
        steps:
        -   name: Checkout
            uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
            with:
                fetch-depth: 0  # Needed for Sonarqube to know about the past context
            
        -   name: Setup Language Toolchain
            uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 #v7.0.0
            with:
                node-version: '20'
                cache: 'npm'
                cache-dependency-path: '${{ matrix.service }}/package-lock.json'
        # Setup Node action automatically uses actions/setup-cache so, no need to use
        # separate step to cache the deps
        
        -   name: Install dependencies
            working-directory: ${{ matrix.service }}
            run:
                npm ci
            
        -   name: Linting
            working-directory: ${{ matrix.service }}
            run:
                npm run lint
        
        -   name: Frontend Unit Tests
            if: ${{ matrix.service == 'frontend' }}
            continue-on-error: true
            working-directory: ${{ matrix.service }}
            run:
                npm run test

        -   name: Backend Unit Tests
            if: ${{ matrix.service == 'backend' }}
            working-directory: ${{ matrix.service }}
            run:
                npm run test:unit
        
        # Security Scan with Sonarqube
        -   name: SonarQube Scan
            uses: SonarSource/sonarqube-scan-action@v8.2.1
            env:
                SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
